load-balancer:
  build: ./load-balancer
  links:
    - worker1:worker1
    - worker2:worker2
    - worker3:worker3
  ports:
    - "3000:3000"
worker1:
  build: ./worker
  links:
    - queue
  ports:
    - "8080"
worker2:
  build: ./worker
  links:
    - queue
  ports:
    - "8080"
worker3:
  build: ./worker
  links:
    - queue
  ports:
    - "8080"
queue:
  image: queue
  ports:
    - "6379"
